// Canonical tool catalog shared between Straja Agent and Straja Vault.
// Keep tool names lowercase and normalized here.

export const TOOL_GROUPS: Record<string, string[]> = {
  "group:memory": ["memory_search", "memory_get", "vault_memory_search", "vault_memory_get"],
  "group:web": ["web_search", "web_fetch", "vault_web_search_duckduckgo", "vault_web_fetch"],
  "group:fs": ["read", "write", "edit", "apply_patch"],
  "group:runtime": ["exec", "process", "vault_exec", "vault_process"],
  "group:sessions": [
    "sessions_list",
    "sessions_history",
    "sessions_send",
    "sessions_spawn",
    "subagents",
    "session_status",
  ],
  "group:ui": ["browser", "canvas"],
  "group:artifacts": [
    "vault_artifact_write",
    "vault_artifact_list",
    "vault_presentation_build",
    "vault_report_build",
    "vault_artifact_url",
    "vault_agent_collection_create",
    "vault_agent_collection_write",
    "vault_collection_write",
    "vault_agent_collection_list",
  ],
  "group:calendar": [
    "vault_gcalendar_create_event",
    "vault_gcalendar_update_event",
    "vault_gcalendar_delete_event",
  ],
  "group:github_api": [
    "vault_github_create_issue",
    "vault_github_list_issues",
    "vault_github_create_branch",
    "vault_github_create_pr",
    "vault_github_list_prs",
    "vault_github_push",
  ],
  "group:developer": ["vault_repo_exec", "vault_repos_list"],
  "group:vault_browser": [
    "vault_browser_navigate",
    "vault_browser_snapshot",
    "vault_browser_click",
    "vault_browser_type",
    "vault_browser_fill",
    "vault_browser_select",
    "vault_browser_hover",
    "vault_browser_press_key",
    "vault_browser_screenshot",
    "vault_browser_tab_list",
    "vault_browser_tab_new",
    "vault_browser_tab_close",
    "vault_browser_tabs",
    "vault_browser_pdf",
    "vault_browser_dialog",
    "vault_stage_media_upload",
    "vault_browser_upload",
    "vault_browser_status",
    "vault_browser_start",
    "vault_browser_stop",
    "vault_browser_console",
    "vault_browser_wait",
    "vault_approve_domain",
  ],
  "group:vault_read": [
    "vault_search",
    "vault_get",
    "vault_multi_get",
    "vault_status",
    "vault_spreadsheet_get",
    "vault_spreadsheet_match",
  ],
  "group:vault_write": [
    "vault_note_create",
    "vault_note_update",
    "vault_memory_write",
    "vault_agent_collection_create",
    "vault_agent_collection_write",
    "vault_collection_write",
    "vault_agent_collection_list",
    "vault_artifact_write",
    "vault_artifact_list",
    "vault_artifact_url",
    "vault_presentation_build",
    "vault_report_build",
    "vault_spreadsheet_update",
  ],
  "group:gmail": ["vault_gmail_create_draft", "vault_gmail_update_draft"],
  "group:automation": ["vault_cron", "gateway"],
  "group:messaging": ["message"],
  "group:nodes": ["nodes"],
  "group:openclaw": [
    "browser",
    "canvas",
    "nodes",
    "vault_cron",
    "message",
    "gateway",
    "agents_list",
    "sessions_list",
    "sessions_history",
    "sessions_send",
    "sessions_spawn",
    "subagents",
    "session_status",
    "memory_search",
    "memory_get",
    "web_search",
    "web_fetch",
    "vault_web_fetch",
    "image",
  ],
};

export const USER_FACING_TOOL_GROUPS: Record<string, string[]> = {
  Memory: ["vault_memory_search", "vault_memory_get", "vault_memory_write"],
  Web: ["vault_web_search_duckduckgo", "vault_web_fetch", "vault_approve_domain"],
  Sessions: [
    "sessions_list",
    "sessions_history",
    "sessions_send",
    "sessions_spawn",
    "subagents",
    "session_status",
  ],
  "Collections & Artifacts": [
    "vault_note_create",
    "vault_note_update",
    "vault_agent_collection_create",
    "vault_agent_collection_write",
    "vault_collection_write",
    "vault_agent_collection_list",
    "vault_artifact_write",
    "vault_artifact_list",
    "vault_artifact_url",
    "vault_presentation_build",
    "vault_report_build",
  ],
  Calendar: [
    "vault_gcalendar_create_event",
    "vault_gcalendar_update_event",
    "vault_gcalendar_delete_event",
  ],
  Gmail: ["vault_gmail_create_draft", "vault_gmail_update_draft"],
  "Vault Browser": [
    "vault_browser_navigate",
    "vault_browser_snapshot",
    "vault_browser_click",
    "vault_browser_type",
    "vault_browser_fill",
    "vault_browser_select",
    "vault_browser_hover",
    "vault_browser_press_key",
    "vault_browser_screenshot",
    "vault_browser_tab_list",
    "vault_browser_tab_new",
    "vault_browser_tab_close",
    "vault_browser_tabs",
    "vault_browser_pdf",
    "vault_browser_dialog",
    "vault_stage_media_upload",
    "vault_browser_upload",
    "vault_browser_status",
    "vault_browser_start",
    "vault_browser_stop",
    "vault_browser_console",
    "vault_browser_wait",
  ],
  "Vault Search & Read": [
    "vault_search",
    "vault_get",
    "vault_multi_get",
    "vault_status",
    "vault_spreadsheet_get",
    "vault_spreadsheet_match",
  ],
  "Vault Write": ["vault_spreadsheet_update"],
  Automation: ["vault_cron", "gateway"],
  Messaging: ["message"],
  "Agents & Nodes": ["nodes", "agents_list", "image"],
  Developer: [
    "vault_repo_exec",
    "vault_repos_list",
    "vault_process",
    "vault_github_create_issue",
    "vault_github_list_issues",
    "vault_github_create_branch",
    "vault_github_create_pr",
    "vault_github_list_prs",
    "vault_github_push",
  ],
};

export const ALL_KNOWN_TOOLS = Array.from(new Set(Object.values(USER_FACING_TOOL_GROUPS).flat()));

export const CHIEF_OF_STAFF_DENYLIST = [
  "vault_repo_exec",
  "vault_repos_list",
  "vault_process",
  "vault_github_create_issue",
  "vault_github_list_issues",
  "vault_github_create_branch",
  "vault_github_create_pr",
  "vault_github_list_prs",
  "vault_github_push",
] as const;
